// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNgYE7Av7ZvtwM1XSfltYBwrGLLw5wbFE',
    appId: '1:620180010394:web:57330a4c3fc4666125b623',
    messagingSenderId: '620180010394',
    projectId: 'gozgon-life-156c8',
    authDomain: 'gozgon-life-156c8.firebaseapp.com',
    storageBucket: 'gozgon-life-156c8.firebasestorage.app',
    measurementId: 'G-5GL4EPN8VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdhbpB5A8BSA58FxhHVGl8GvBiyoD06LI',
    appId: '1:620180010394:android:8d72cad2a9dbdbdf25b623',
    messagingSenderId: '620180010394',
    projectId: 'gozgon-life-156c8',
    storageBucket: 'gozgon-life-156c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5b7tyqxVq7YpmRZynZq7Q9k0A7FE8LLw',
    appId: '1:620180010394:ios:aa8467d73c81df7a25b623',
    messagingSenderId: '620180010394',
    projectId: 'gozgon-life-156c8',
    storageBucket: 'gozgon-life-156c8.firebasestorage.app',
    iosBundleId: 'com.example.gozgonLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5b7tyqxVq7YpmRZynZq7Q9k0A7FE8LLw',
    appId: '1:620180010394:ios:aa8467d73c81df7a25b623',
    messagingSenderId: '620180010394',
    projectId: 'gozgon-life-156c8',
    storageBucket: 'gozgon-life-156c8.firebasestorage.app',
    iosBundleId: 'com.example.gozgonLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNgYE7Av7ZvtwM1XSfltYBwrGLLw5wbFE',
    appId: '1:620180010394:web:6543d05cfdfacd0b25b623',
    messagingSenderId: '620180010394',
    projectId: 'gozgon-life-156c8',
    authDomain: 'gozgon-life-156c8.firebaseapp.com',
    storageBucket: 'gozgon-life-156c8.firebasestorage.app',
    measurementId: 'G-5L22ZNVTMW',
  );
}
